language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
script:
  - python setup.py test
deploy:
  - provider: pypi
    user: yylucifer
    password: ${PYPI_PASSWORD}
    on:
      python: 2.7
      tags: true
      branch: master
  - provider: pypi
    user: yylucifer
    password: ${PYPI_PASSWORD}
    on:
      python: 3.6
      tags: true
      branch: master